version: '3.8'

services:
  gabigabi:
    image: guerrini:dl
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: always
    ports:
      - 3019:3000
    volumes:
      - /var/guerrini:/home/storage
    environment:
      - NODE_ENV=production
